---
- name: haproxy configuration
  hosts: ansible5
  vars:
  - haproxy_frontend_port: 8080
  - haproxy_backend_servers:
    - name: app1
      address: ansible1:80
    - name: app2
      address: ansible2:80
  roles:
  - geerlingguy.haproxy
  tasks:
  - name: ouverture des ports
    firewalld:
      port: 8080/tcp
      immediate: yes
      permanent: yes
      state: enabled
- name: ouverture du port chez l'hote ansible1
  hosts: ansible1
  tasks:
  - name: ouverture des ports
    firewalld:
      port: 80/tcp
      immediate: yes
      permanent: yes
      state: enabled
