---
- name: create cgroup
  hosts: localhost
  tasks:
  - name: install the required package
    yum:
      name: libcgroup-tools
      state: latest
  - name: create the cgroup
    command: cgcreate -a ansible:ansible -t ansible:ansible -g  cpuacct,memory,pids:ansible_profile
